### ISSUE TITLE
Integrate Docker Sync library to speed up development process

### ISSUE THREAD

**Issue by ArthurZaharov** [fs/rails-base-graphql-api#38]
http://docker-sync.io/
https://github.com/EugenMayer/docker-sync

**Comment by EvgeniyEsaulkov** [comment]
I tested this library on my local machine also as [`cached` strategy for volumes](https://docs.docker.com/docker-for-mac/osxfs-caching/). For volumes that mount some directories from host there is a really significant performance increase:

App directory mounted with `:cached` option:
```
› docker exec -it rails-base-graphql-api_app_1 time dd if=/dev/zero of=/app/test/test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
real  0m 31.82s
user  0m 0.21s
sys 0m 1.75s
```

App directory mounted via docker-sync:
```
› docker exec -it rails-base-graphql-api_app_1 time dd if=/dev/zero of=/app/test/test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
real  0m 0.43s
user  0m 0.07s
sys 0m 0.32s
```

For content generated inside container there are no difference.

So we can integrate this library as the most of our developers use Mac OSX. But we have to add instructions for Linux/Windows how to install dependencies for this tools. And we need a separate `docker-compose` config for Semaphore CI, because it will slow down the build (docker-sync creates a separate volume at first run - it takes 2-3 minutes).
